## This is numpy assignment consists of 11 questions


In [ ]:
import numpy as np

In [ ]:
#1. Create a 5X2 integer array from a range between 100 to 200 such that the
#difference between each element is 10 (Hint arange function)

array=np.arange(100, 200, 11)
print(array)

[100 111 122 133 144 155 166 177 188 199]


In [16]:
#2. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives
array1=np.zeros(10)
array2=np.ones(10)
array3=np.full(5,5)
print(array1)
print(array2)
print(array3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5]


In [ ]:
#3. Write a NumPy program to generate an 4x7 array of random numbers between 0 and 1 
array=np.random.rand(4,7)
print(array)


[[0.92930294 0.4382177  0.82754046 0.68595808 0.44757744 0.37028992
  0.67303929]
 [0.68815666 0.18329901 0.41926596 0.40154392 0.03640649 0.55203037
  0.96711656]
 [0.0225348  0.51213735 0.79175857 0.25794425 0.37693369 0.5738605
  0.92614934]
 [0.10578393 0.45769344 0.23515752 0.36562324 0.96659177 0.53025881
  0.79334492]]


In [21]:
#4 Declare the following provided numPy array and print array items the third
#column from all rows [[11 ,22, 33], [44, 55, 66], [77, 88, 99]]
array = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print(array[:, 2]) # print third column from all rows

[33 66 99]


In [26]:
#5. Return array of odd rows and even columns from below numpy array
sampleArray = np.array(
    [
            [3 ,6, 9, 12], 
     [15 ,18, 21, 24], 
            [27 ,30, 33, 36],
     [39 ,42, 45, 48], 
            [51 ,54, 57, 60]
     ]
    )
print(sampleArray[::2, 1::2]) # odd rows and even columns


[[ 6 12]
 [30 36]
 [54 60]]


In [29]:
#6. Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
resultArray=arrayOne + arrayTwo
resultArray = np.square(resultArray) # square of each element
print(resultArray)


[[ 400 1521 1089]
 [ 625  625  784]]


In [31]:
# 7. Print max from axis 0 and min from axis 1 from the following 2-D array
sampleArray = np.array([
    [34,43,73],
    [82,22,12],
    [53,94,66]
    ])
print("Max from axis 0:", sampleArray.max(axis=0)) # max from axis 0
print("Min from axis 1:", sampleArray.min(axis=1)) # min from axis 1

Max from axis 0: [82 94 73]
Min from axis 1: [34 12 53]


In [33]:
# 8. Delete the second column from a given array and insert the following new column in its place.
sampleArray = np.array([
     [34,43,73],
     [82,22,12],
     [53,94,66]
     ])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 1, axis=1) # delete second column
print("Original array:\n", sampleArray)

Original array:
 [[34 73]
 [82 12]
 [53 66]]


In [36]:
#9. Print the transpose of the array ([[1,2,3], [4,5,6], [7,8,9]])
array=np.array([[1,2,3], [4,5,6], [7,8,9]]).T
print(array)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [48]:
#10.Convert the following 1D array to a 2D array with 2 rows
array=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array.reshape((2,-1))) # 2 rows and as many columns as needed


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [49]:
# 11.Create a NumPy array of shape (4, 4) and calculate the sum of all elements, the sum along each row, and the sum along each column.
array = np.random.randint(1, 10, (4, 4)) # random integers between 1 and 10
print("Array:\n", array)
array_sum = np.sum(array) # sum of all elements
print("Sum of all elements:", array_sum)

Array:
 [[2 8 8 5]
 [2 6 1 4]
 [9 9 7 1]
 [7 7 7 6]]
Sum of all elements: 89
